// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ÖdemeServisi.Concrete;

namespace ÖdemeServisi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220501192418_kredikartıentity_sonkullanımtarihiproperty")]
    partial class kredikartıentity_sonkullanımtarihiproperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ÖdemeServisi.Entities.BankaHesap", b =>
                {
                    b.Property<int>("BankaHesapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BankaHesapBakiye")
                        .HasColumnType("float");

                    b.Property<string>("BankaHesapNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BankaHesapSahibiId")
                        .HasColumnType("int");

                    b.HasKey("BankaHesapId");

                    b.ToTable("BankaHesapları");
                });

            modelBuilder.Entity("ÖdemeServisi.Entities.KrediKartı", b =>
                {
                    b.Property<int>("KrediKartıId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KrediKartıCV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KrediKartıNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KrediKartıSahibiId")
                        .HasColumnType("int");

                    b.Property<int>("KrediKartıSonKullanımTarihi")
                        .HasColumnType("int");

                    b.HasKey("KrediKartıId");

                    b.ToTable("KrediKartları");
                });

            modelBuilder.Entity("ÖdemeServisi.Entities.Odeme", b =>
                {
                    b.Property<int>("OdemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OdemeAcıklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OdemeMiktarı")
                        .HasColumnType("float");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OdemeYapanId")
                        .HasColumnType("int");

                    b.HasKey("OdemeId");

                    b.ToTable("Odemeler");
                });
#pragma warning restore 612, 618
        }
    }
}
